apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bp2vxw5ed-dotnet-basic
  janus-idp.io/tekton: bp2vxw5ed-dotnet-basic
  backstage.io/kubernetes-id: bp2vxw5ed-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bp2vxw5ed-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
